<a href="https://colab.research.google.com/github/reza-debug/Deep_Learning/blob/main/CrossValidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Creation 🍨

In [4]:
from sklearn.datasets import make_classification

X,y = make_classification(n_samples=1000, n_features=10, n_informative=8, n_redundant=2, random_state=0, n_classes=2)



In [10]:
X[0]

array([ 0.59748132,  2.03702154,  0.63388218,  2.89010949,  1.30628617,
       -0.52502013,  0.19653851, -0.58915931, -0.5775684 , -2.07947151])

In [11]:
y[0]

1

In [5]:
import tensorflow as tf
from tensorflow import keras

## Function for create model 🤭

In [6]:
def create_model():
  model = keras.Sequential()
  model.add(keras.layers.Dense(units=1, activation='relu'))
  model.add(keras.layers.Dense(units=1, activation='sigmoid'))

  model.compile(optimizer= 'Adam', loss = tf.losses.binary_crossentropy, metrics= ['Accuracy'])
  return model

## Cross Validation 🎷

In [7]:
n_split = 5
#5 fold made by stratifiedFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

kf = StratifiedKFold( n_splits=n_split, shuffle=True )


In [8]:
#save all of acc from each fold
#the best will be in mean of acc_total
acc_total = []

In [20]:
kf

StratifiedKFold(n_splits=5, random_state=None, shuffle=True)

In [21]:
for train_index, validation_index in kf.split(X,y):
  X_train = X[ train_index ]
  y_train = y[ train_index ]

  X_validation = X[ validation_index ]
  y_validation = y[ validation_index ]


In [19]:
X_train[0]

array([ 0.59748132,  2.03702154,  0.63388218,  2.89010949,  1.30628617,
       -0.52502013,  0.19653851, -0.58915931, -0.5775684 , -2.07947151])

In [23]:
X_validation[0]

array([-0.23299237,  1.22911085,  3.4409557 ,  1.79295895, -2.76256638,
       -3.03480131, -0.7260982 ,  0.32869221,  1.33281026,  0.642329  ])

In [24]:
y_train[0]

1

In [25]:
y_validation[0]

1

# Model 💠

In [32]:
from re import VERBOSE
model = create_model()
model.fit( X_train, y_train, epochs=20 , batch_size=64, validation_data = ( X_validation, y_validation ), verbose= 1 )
#verbose for show info (0,1,2)

Epoch 1/20
13/13 [==============================] - 1s 17ms/step - loss: 0.8353 - Accuracy: 0.6550 - val_loss: 0.8149 - val_Accuracy: 0.6450
Epoch 2/20
13/13 [==============================] - 0s 6ms/step - loss: 0.8039 - Accuracy: 0.6662 - val_loss: 0.7802 - val_Accuracy: 0.6550
Epoch 3/20
13/13 [==============================] - 0s 7ms/step - loss: 0.7743 - Accuracy: 0.6762 - val_loss: 0.7490 - val_Accuracy: 0.6600
Epoch 4/20
13/13 [==============================] - 0s 6ms/step - loss: 0.7476 - Accuracy: 0.6850 - val_loss: 0.7201 - val_Accuracy: 0.6650
Epoch 5/20
13/13 [==============================] - 0s 6ms/step - loss: 0.7224 - Accuracy: 0.7000 - val_loss: 0.6941 - val_Accuracy: 0.6700
Epoch 6/20
13/13 [==============================] - 0s 5ms/step - loss: 0.7003 - Accuracy: 0.7088 - val_loss: 0.6711 - val_Accuracy: 0.6750
Epoch 7/20
13/13 [==============================] - 0s 7ms/step - loss: 0.6805 - Accuracy: 0.7200 - val_loss: 0.6510 - val_Accuracy: 0.6800
Epoch 8/20
13/13 [=

# Prediction ♒

In [33]:
y_pred = model.predict(X_validation)
y_pred

7/7 [==============================] - 0s 2ms/step


array([[0.64896137],
       [0.95295113],
       [0.4443584 ],
       [0.98353505],
       [0.5158197 ],
       [0.90888494],
       [0.99999726],
       [0.4443584 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.9998056 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.99350053],
       [0.99689317],
       [0.4443584 ],
       [0.4443584 ],
       [0.9964515 ],
       [0.4443584 ],
       [0.5960435 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.6662618 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.98881793],
       [0.937203  ],
       [0.9487888 ],
       [0.9357537 ],
       [0.4443584 ],
       [0.4486299 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.4443584 ],
       [0.95363736],
       [0.4443584 ],
       [0.8690925 ],
       [0.9435234 ],
       [0.9042956 ],
       [0.4443584 ],
       [0.6680216 ],
       [0.4443584 ],
       [0.444