<a href="https://colab.research.google.com/github/reza-debug/Deep_Learning/blob/main/CrossValidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Creation 🍨

In [193]:
from sklearn.datasets import make_classification

X,y = make_classification(n_samples=1000, n_features=10, n_informative=8, n_redundant=2, random_state=0, n_classes=2)



In [194]:
X[0]

array([ 0.59748132,  2.03702154,  0.63388218,  2.89010949,  1.30628617,
       -0.52502013,  0.19653851, -0.58915931, -0.5775684 , -2.07947151])

In [195]:
y[0]

1

In [196]:
import tensorflow as tf
from tensorflow import keras

## Function for create model 🤭

In [197]:
def create_model():
  model = keras.Sequential()
  model.add(keras.layers.Dense(units=1, activation='relu'))
  model.add(keras.layers.Dense(units=1, activation='sigmoid'))

  model.compile(optimizer= 'Adam', loss = tf.losses.binary_crossentropy, metrics= ['Accuracy'])
  return model

## Cross Validation 🎷

In [198]:
n_split = 5
#5 fold made by stratifiedFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

kf = StratifiedKFold( n_splits = n_split, shuffle=True )


In [199]:
#save all of acc from each fold
#the best will be in mean of acc_total
acc_total = []

In [200]:
kf

StratifiedKFold(n_splits=5, random_state=None, shuffle=True)

In [201]:
for train_index, validation_index in kf.split(X,y):
  X_train = X[ train_index ]
  y_train = y[ train_index ]

  X_validation = X[ validation_index ]
  y_validation = y[ validation_index ]
  #5bar ba flot dar makanhaye mokhtalef hesab mishavad
  model = create_model()
  model.fit( X_train, y_train, epochs=20 , batch_size=64, validation_data = ( X_validation, y_validation ), verbose= 1 )
  #verbose for show info (0,1,2)

  y_pred = model.predict(X_validation)
  #change float to int
  y_pred = (y_pred > 0.5).astype("int32")

  #all of acc in one list
  acc = accuracy_score( y_true= y_validation, y_pred= y_pred )
  acc_total.append(acc)




Epoch 1/20
13/13 [==============================] - 1s 17ms/step - loss: 1.1447 - Accuracy: 0.5512 - val_loss: 1.0626 - val_Accuracy: 0.5600
Epoch 2/20
13/13 [==============================] - 0s 5ms/step - loss: 1.1047 - Accuracy: 0.5700 - val_loss: 1.0274 - val_Accuracy: 0.5700
Epoch 3/20
13/13 [==============================] - 0s 7ms/step - loss: 1.0684 - Accuracy: 0.5750 - val_loss: 0.9937 - val_Accuracy: 0.5950
Epoch 4/20
13/13 [==============================] - 0s 7ms/step - loss: 1.0343 - Accuracy: 0.5863 - val_loss: 0.9633 - val_Accuracy: 0.6050
Epoch 5/20
13/13 [==============================] - 0s 6ms/step - loss: 1.0014 - Accuracy: 0.5950 - val_loss: 0.9357 - val_Accuracy: 0.6050
Epoch 6/20
13/13 [==============================] - 0s 6ms/step - loss: 0.9708 - Accuracy: 0.6037 - val_loss: 0.9097 - val_Accuracy: 0.6150
Epoch 7/20
13/13 [==============================] - 0s 5ms/step - loss: 0.9440 - Accuracy: 0.6162 - val_loss: 0.8836 - val_Accuracy: 0.6250
Epoch 8/20
13/13 [=

In [202]:
acc_total

[0.715, 0.775, 0.745, 0.445, 0.535]

In [203]:
X_train[0]

array([ 0.59748132,  2.03702154,  0.63388218,  2.89010949,  1.30628617,
       -0.52502013,  0.19653851, -0.58915931, -0.5775684 , -2.07947151])

In [204]:
X_validation[0]

array([-1.39824804, -2.58030896, -0.04082532,  1.31024751, -1.38100493,
        0.52963921, -2.63620481, -3.59222013,  2.57568717,  0.97952144])

In [205]:
y_validation[0]

1

In [206]:
y_train.shape

(800,)

In [207]:
X_train.shape

(800, 10)

In [208]:
X_validation.shape

(200, 10)

In [209]:
y_pred.shape

(200, 1)