<a href="https://colab.research.google.com/github/reza-debug/Deep_Learning/blob/main/CrossValidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Creation 🍨

In [19]:
from sklearn.datasets import make_classification

X,y = make_classification(n_samples=1000, n_features=10, n_informative=8, n_redundant=2, random_state=0, n_classes=2)



In [20]:
X[0]

array([ 0.59748132,  2.03702154,  0.63388218,  2.89010949,  1.30628617,
       -0.52502013,  0.19653851, -0.58915931, -0.5775684 , -2.07947151])

In [21]:
y[0]

1

In [22]:
import tensorflow as tf
from tensorflow import keras

## Function for create model 🤭

In [23]:
def create_model():
  model = keras.Sequential()
  model.add(keras.layers.Dense(units=20, activation='relu'))
  model.add(keras.layers.Dense(units=1, activation='sigmoid'))

  model.compile(optimizer= 'Adam', loss = tf.losses.binary_crossentropy, metrics= ['Accuracy'])
  return model

## Cross Validation 🎷

In [24]:
n_split = 5
#5 fold made by stratifiedFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

kf = StratifiedKFold( n_splits = n_split, shuffle=True )


In [25]:
#save all of acc from each fold
#the best will be in mean of acc_total
acc_total = []

In [26]:
kf

StratifiedKFold(n_splits=5, random_state=None, shuffle=True)

In [27]:
for train_index, validation_index in kf.split(X,y):
  X_train = X[ train_index ]
  y_train = y[ train_index ]

  X_validation = X[ validation_index ]
  y_validation = y[ validation_index ]
  #5bar ba flot dar makanhaye mokhtalef hesab mishavad
  model = create_model()
  model.fit( X_train, y_train, epochs=20 , batch_size=64, validation_data = ( X_validation, y_validation ), verbose= 1 )
  #verbose for show info (0,1,2)

  y_pred = model.predict(X_validation)
  #change float to int
  y_pred = (y_pred > 0.5).astype("int32")

  #all of acc in one list
  acc = accuracy_score( y_true= y_validation, y_pred= y_pred )
  acc_total.append(acc)




Epoch 1/20
13/13 [==============================] - 2s 23ms/step - loss: 1.0228 - Accuracy: 0.5063 - val_loss: 0.9073 - val_Accuracy: 0.5700
Epoch 2/20
13/13 [==============================] - 0s 5ms/step - loss: 0.8695 - Accuracy: 0.5650 - val_loss: 0.7828 - val_Accuracy: 0.6200
Epoch 3/20
13/13 [==============================] - 0s 6ms/step - loss: 0.7429 - Accuracy: 0.6137 - val_loss: 0.6818 - val_Accuracy: 0.6900
Epoch 4/20
13/13 [==============================] - 0s 7ms/step - loss: 0.6414 - Accuracy: 0.6513 - val_loss: 0.6022 - val_Accuracy: 0.7200
Epoch 5/20
13/13 [==============================] - 0s 6ms/step - loss: 0.5647 - Accuracy: 0.7075 - val_loss: 0.5405 - val_Accuracy: 0.7500
Epoch 6/20
13/13 [==============================] - 0s 5ms/step - loss: 0.5040 - Accuracy: 0.7487 - val_loss: 0.4935 - val_Accuracy: 0.7650
Epoch 7/20
13/13 [==============================] - 0s 6ms/step - loss: 0.4604 - Accuracy: 0.7875 - val_loss: 0.4572 - val_Accuracy: 0.7650
Epoch 8/20
13/13 [=

In [28]:
acc_total

[0.945, 0.895, 0.95, 0.905, 0.915]

In [29]:
X_train[0]

array([-2.69676861,  0.74564836, -1.67641125,  2.69969282, -5.01357815,
        3.10557956,  1.30169376,  2.03240389,  2.1138015 ,  0.98205628])

In [30]:
X_validation[0]

array([ 0.59748132,  2.03702154,  0.63388218,  2.89010949,  1.30628617,
       -0.52502013,  0.19653851, -0.58915931, -0.5775684 , -2.07947151])

In [31]:
y_validation[0]

1

In [32]:
y_train.shape

(800,)

In [33]:
X_train.shape

(800, 10)

In [34]:
X_validation.shape

(200, 10)

In [35]:
y_pred.shape

(200, 1)

# Accuracy for all of them 🤩

In [36]:
import numpy as np
np.mean(acc_total)

0.922